import { useId, useState, type CSSProperties, type FormEvent, type ReactNode } from 'react'
import { IonBadge, IonCheckbox, IonIcon, IonInput, IonItem, IonLabel, IonList, IonNote, IonPopover, IonRadio, IonRadioGroup, IonSelect, IonSelectOption, IonSpinner, IonToggle } from '@ionic/react'
import { addOutline, arrowForwardOutline, bookmark, bookmarkOutline, cameraOutline, checkmarkOutline, chevronDownOutline, closeOutline, compassOutline, documentOutline, imageOutline, openOutline, searchOutline, settingsOutline } from 'ionicons/icons'
import { IosButton as Button } from '../components/ui/ios-button'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '../components/ui/accordion'
import { places, placeIds, suggestionsFor, type Exchange, type Interest, type PlaceId } from '../lib/places'
import { resolveToken } from '../design-system/tokens'
import './design-system-examples.css'

const source = (path: string) => `source/src/${path}`
const ionicPreviewTheme = {
  '--ion-font-family': 'var(--font-body)',
  '--ion-background-color': 'var(--card)',
  '--ion-item-background': 'var(--card)',
  '--ion-text-color': 'var(--foreground)',
  '--ion-border-color': 'var(--border)',
  '--ion-color-primary': 'var(--primary)',
  '--ion-color-primary-contrast': 'var(--primary-foreground)',
  '--ion-color-primary-shade': 'var(--primary-hover)',
  '--ion-color-primary-tint': 'var(--primary-active)',
} as CSSProperties
const interestOptions: { label: string; value: Interest }[] = [
  { label: 'Everything', value: 'A little of everything' },
  { label: 'Architecture', value: 'Art & architecture' },
  { label: 'Greenery', value: 'Hidden greenery' },
]

function Section({ title, children }: { title: string; children: ReactNode }) {
  return <section className="dse-section"><h2>{title}</h2>{children}</section>
}

function Code({ children }: { children: string }) {
  return <pre className="dse-code"><code>{children}</code></pre>
}

function Contract({ implementation, path, props, tokens }: { implementation: string; path: string; props: [string, string][]; tokens: string[] }) {
  return <Section title="Implementation"><p>{implementation} <a className="ds-inline-code-link" href={source(path)} target="_blank" rel="noreferrer">View source <IonIcon icon={openOutline} className="dse-icon-sm" aria-hidden="true" /></a></p><div className="ds-table-wrap dse-contract-table"><table><thead><tr><th>API / behavior</th><th>Contract</th></tr></thead><tbody>{props.map(([name, value]) => <tr key={name}><th scope="row"><code>{name}</code></th><td>{value}</td></tr>)}</tbody></table></div><h3>Token dependencies</h3><p className="dse-tokens">{tokens.map(token => <code key={token}>{token}</code>)}</p><p className="ds-note">Component-specific tokens are deferred. These examples consume the shared semantic layer.</p></Section>
}

function IconsPage() {
  const icons = [{ name: 'searchOutline', icon: searchOutline, meaning: 'Find a place' }, { name: 'addOutline', icon: addOutline, meaning: 'Add an attachment' }, { name: 'checkmarkOutline', icon: checkmarkOutline, meaning: 'Selected or complete' }, { name: 'closeOutline', icon: closeOutline, meaning: 'Close or clear' }, { name: 'chevronDownOutline', icon: chevronDownOutline, meaning: 'Open a selection' }, { name: 'settingsOutline', icon: settingsOutline, meaning: 'Adjust preferences' }]
  return <>
    <p>The phone app uses Ionicons through Ionic’s <code>IonIcon</code>. Keep one icon treatment within a control group. Marketing and the documentation shell retain Lucide.</p>
    <Section title="App icon set"><div className="ds-panel dse-icon-grid">{icons.map(({ name, icon, meaning }) => <div key={name}><IonIcon icon={icon} className="dse-icon-lg" aria-hidden="true" /><strong>{name}</strong><span>{meaning}</span></div>)}</div><Code>{"import { IonIcon } from '@ionic/react'\nimport { searchOutline } from 'ionicons/icons'"}</Code><p className="ds-note">These are Ionicons, not Apple’s SF Symbols. Import the icon data directly from the installed package.</p></Section>
    <Section title="Size and alignment"><div className="ds-panel dse-icon-sizes">{['sm', 'md', 'lg'].map(size => <div key={size}><IonIcon icon={searchOutline} className={`dse-icon-${size}`} aria-hidden="true" /><code>--icon-{size}</code><span>{resolveToken(`--icon-${size}`, 'light')}</span></div>)}</div><p>Center the icon inside its control. Icon dimensions are separate from the hit area: use at least <code>--target-min</code> for touch controls.</p></Section>
    <Section title="Accessible usage"><p>Hide decorative icons with <code>aria-hidden="true"</code>. Name icon-only buttons and keep text alongside unfamiliar actions.</p><Code>{'<IosButton size="icon" aria-label="Search places" onClick={openSearch}>\n  <IonIcon icon={searchOutline} aria-hidden="true" />\n</IosButton>'}</Code><p className="ds-note">The snippet requires the screen’s real <code>openSearch</code> handler. Phone controls keep a 44px touch floor.</p></Section>
    <Contract implementation="The phone app uses IonIcon with imported Ionicons." path="studio/Mockup.tsx" props={[["icon", "Imported SVG data from ionicons/icons."], ["className / style", "Use the existing icon dimensions and inherit the text color."], ["slot", "Use start, end or icon-only within Ionic controls when appropriate."], ["aria-hidden / aria-label", "Hide decorative icons; name the interactive parent."]]} tokens={['--icon-sm', '--icon-md', '--icon-lg', '--target-min', '--foreground', '--muted-foreground']} />
  </>
}

function ButtonPage() {
  const [message, setMessage] = useState('Select an enabled example to inspect its feedback.')
  return <>
    <p>Phone actions use <code>IosButton</code>, the shared adapter around Ionic’s iOS-mode <code>IonButton</code>. Use one primary action, with quieter secondary and ghost actions.</p>
    <Section title="Variants"><div className="ds-panel"><div className="dse-control-row">{[{ name: 'Primary', variant: 'default' }, { name: 'Secondary', variant: 'secondary' }, { name: 'Ghost', variant: 'ghost' }, { name: 'Light surface', variant: 'light' }].map(({ name, variant }) => <div className="dse-labeled-control" key={variant}><Button variant={variant as 'default' | 'secondary' | 'ghost' | 'light'} onClick={() => setMessage(`${name} example selected.`)}>{name}</Button><code>variant="{variant}"</code></div>)}</div><p className="dse-status" role="status">{message}</p></div><p className="ds-note">Primary and light variants use solid fill, secondary uses outline and ghost uses clear. Placewise supplies the typography and colors; Ionic supplies the control geometry and interaction states.</p></Section>
    <Section title="Sizes and states"><div className="ds-panel"><div className="dse-control-row"><div className="dse-labeled-control"><Button onClick={() => setMessage('Default-size action selected.')}>Explore the example<IonIcon icon={arrowForwardOutline} slot="end" aria-hidden="true" /></Button><code>size="default"</code></div><div className="dse-labeled-control"><Button size="sm" variant="secondary" onClick={() => setMessage('Small action selected.')}>Update places</Button><code>size="sm"</code></div><div className="dse-labeled-control"><Button size="icon" aria-label="Add example place" onClick={() => setMessage('Icon action selected. No place was created.')}><IonIcon icon={addOutline} slot="icon-only" aria-hidden="true" /></Button><code>size="icon"</code></div><div className="dse-labeled-control"><Button disabled>Update places</Button><span>Disabled</span></div><div className="dse-labeled-control"><Button disabled aria-busy="true"><IonSpinner name="lines-small" slot="start" aria-hidden="true" />Finding places</Button><span>Loading specimen</span></div></div></div><p>Keep a 44px touch floor, including compact and icon controls. Use the actual Ionic hover, pressed, focus and disabled states. The loading specimen runs no request.</p></Section>
    <Section title="Composition"><Code>{'<IosButton variant="secondary" disabled={!hasChanges} onClick={updatePlaces}>\n  Update places\n</IosButton>'}</Code><p>Use a button for actions and <code>href</code> for navigation. Set <code>type="submit"</code> only for the form’s submit action. The adapter defaults to <code>type="button"</code>.</p></Section>
    <Contract implementation="Shared IosButton wraps IonButton and always selects iOS mode. The marketing page and documentation shell retain the base shadcn Button." path="components/ui/ios-button.tsx" props={[["variant", "default (solid), secondary (outline), ghost (clear), light (solid)."], ["size", "default, sm or icon; the adapter maps these to Ionic size and shape."], ["fill / expand / shape", "Optional Ionic overrides for real component composition."], ["disabled / type / aria-*", "Ionic attributes and state are forwarded. Compose IonSpinner with a visible loading label."], ["ref", "HTMLIonButtonElement host. Its focusable native control lives in the shadow root."]]} tokens={['--primary', '--primary-foreground', '--secondary', '--secondary-foreground', '--disabled', '--disabled-foreground', '--target-min', '--ring', '--focus-width', '--focus-offset']} />
  </>
}

function TogglePage() {
  const [coffee, setCoffee] = useState(true)
  const [architecture, setArchitecture] = useState(true)
  return <>
    <p>Use <code>IonToggle</code> for an on/off setting, such as the planner’s Coffee stop. Use <code>IonCheckbox</code> for independent interests that can be selected together.</p>
    <Section title="Settings and independent choices"><div className="ds-panel"><IonList mode="ios" lines="full"><IonItem mode="ios"><IonToggle mode="ios" checked={coffee} onIonChange={event => setCoffee(event.detail.checked)} justify="space-between">Coffee stop</IonToggle></IonItem><IonItem mode="ios"><IonCheckbox mode="ios" checked={architecture} onIonChange={event => setArchitecture(event.detail.checked)} justify="space-between" labelPlacement="start">Architecture</IonCheckbox></IonItem><IonItem mode="ios"><IonCheckbox mode="ios" disabled justify="space-between" labelPlacement="start">Unavailable interest</IonCheckbox></IonItem></IonList><p className="dse-status" role="status">Coffee is {coffee ? 'included' : 'off'}. Architecture is {architecture ? 'selected' : 'not selected'}. These choices stay in the documentation preview.</p></div><p>Keep labels stable and expose the checked state through the component. A switch changes a setting; a checkbox selects one item in a set. Explain disabled choices when the reason affects the next step.</p></Section>
    <Section title="Composition"><Code>{'<IonToggle mode="ios" checked={coffee}\n  onIonChange={event => setCoffee(event.detail.checked)}>\n  Coffee stop\n</IonToggle>'}</Code></Section>
    <Contract implementation="The phone planner imports IonToggle and IonCheckbox directly. No extra shared wrapper is needed." path="studio/Mockup.tsx" props={[["mode", "ios for the phone interaction and component geometry."], ["checked / onIonChange", "Controlled state; read event.detail.checked."], ["disabled", "Prevents changes while keeping the current state visible."], ["children / labelPlacement", "Supply the visible accessible label and its placement."]]} tokens={['--primary', '--primary-foreground', '--foreground', '--input', '--ring', '--disabled', '--disabled-foreground', '--target-min']} />
  </>
}

function RadioPage() {
  const [choice, setChoice] = useState(60)
  return <>
    <p>Use <code>IonRadioGroup</code> and <code>IonRadio</code> when exactly one option must be selected from a short visible set. The walk planner uses this pattern for available time.</p>
    <Section title="Duration choices"><div className="ds-panel"><IonRadioGroup value={choice} onIonChange={event => setChoice(Number(event.detail.value))} aria-label="Time available"><IonList mode="ios" lines="full">{[45, 60, 90].map(minutes => <IonItem mode="ios" key={minutes}><IonRadio mode="ios" value={minutes} justify="space-between" labelPlacement="start">{minutes} minutes</IonRadio></IonItem>)}<IonItem mode="ios"><IonRadio mode="ios" value={120} disabled justify="space-between" labelPlacement="start">120 minutes, unavailable</IonRadio></IonItem></IonList></IonRadioGroup><p className="dse-status" role="status">Selected: {choice} minutes.</p></div><p>Name the group and label every option. Let Ionic manage the group’s keyboard selection and focus behavior; do not add a second click handler that changes the same state.</p></Section>
    <Code>{'<IonRadioGroup value={minutes}\n  onIonChange={event => setMinutes(event.detail.value)}>\n  <IonRadio mode="ios" value={60}>60 minutes</IonRadio>\n</IonRadioGroup>'}</Code>
    <Contract implementation="The phone planner uses Ionic radio components directly." path="studio/Mockup.tsx" props={[["value / onIonChange", "Control the selected value on IonRadioGroup. Read event.detail.value."], ["IonRadio value", "A stable value for each option, matching the group value type."], ["disabled", "Prevents selection of that option."], ["aria-label / children", "Name the group and give each option a visible label."]]} tokens={['--primary', '--foreground', '--muted-foreground', '--ring', '--focus-width', '--focus-offset', '--target-min']} />
  </>
}

function QuestionForm({ id }: { id: string }) {
  const [question, setQuestion] = useState('')
  const [error, setError] = useState('')
  const [answer, setAnswer] = useState<Exchange | null>(null)
  function submit(event: FormEvent) {
    event.preventDefault()
    const normalize = (value: string) => value.toLowerCase().replace(/[?’'?]/g, '').trim()
    const match = places.coit.questions.find(item => normalize(item.question) === normalize(question))
    if (!match) { setError('Try a suggested question in this preview. Your draft is still here.'); setAnswer(null); return }
    setAnswer(match); setError('')
  }
  return <div className="dse-question-example"><form className="dse-form" onSubmit={submit} noValidate><div className="dse-field"><IonInput mode="ios" id={`${id}-question`} label="Your question about Coit Tower" labelPlacement="stacked" value={question} onIonInput={event => { setQuestion(String(event.detail.value ?? '')); setError('') }} maxlength={500} helperText="Prepared answers only. Choose a suggestion or type the same question." errorText={error} className={error ? 'ion-invalid ion-touched' : undefined} autocomplete="off" placeholder="What are you wondering?" />{error && <span className="sr-only" role="alert">{error}</span>}</div><div className="dse-suggestions" aria-label="Suggested questions">{places.coit.questions.slice(0, 2).map(item => <Button variant="ghost" key={item.question} onClick={() => { setQuestion(item.question); setError('') }}>{item.question}<IonIcon icon={openOutline} slot="end" aria-hidden="true" /></Button>)}</div><Button type="submit" disabled={!question.trim()}>Read prepared answer<IonIcon icon={arrowForwardOutline} slot="end" aria-hidden="true" /></Button></form>{answer && <div className="dse-answer" aria-live="polite"><h3>{answer.question}</h3><p>{answer.answer}</p><a href={answer.source} target="_blank" rel="noreferrer">{answer.sourceLabel}<IonIcon icon={openOutline} className="dse-icon-sm" aria-hidden="true" /></a></div>}</div>
}

function TextInputPage() {
  return <>
    <p>Use <code>IonInput</code> for single-line fields and <code>IonTextarea</code> for the chat draft. Keep a visible label, short help and a clear action. Preserve the draft when recovery is needed.</p>
    <Section title="Label, help and recovery"><div className="ds-panel"><QuestionForm id="dse-input" /></div><p>Enter an unsupported question to see validation. Choose a suggestion and submit to recover. This documentation specimen uses prepared Coit Tower answers; it does not send a live request.</p></Section>
    <Section title="Disabled state"><div className="ds-panel dse-form"><IonInput mode="ios" label="Example location" labelPlacement="stacked" value="Telegraph Hill" disabled readonly helperText="This specimen is fixed to the prepared Telegraph Hill example." /></div></Section>
    <Section title="Phone composer"><p>The phone’s <code>IonTextarea</code> stays compact for one or two displayed lines. The third line grows the composer, up to its 120px input limit. Focus alone never enlarges the sheet; sending opens the conversation. Keep that measured sizing when changing the component.</p><Code>{'<IonInput mode="ios" label="Photo location"\n  labelPlacement="stacked" value={location}\n  onIonInput={event => setLocation(event.detail.value ?? "")} />'}</Code></Section>
    <Contract implementation="The phone uses IonInput and IonTextarea directly, with existing draft state and composer measurements." path="studio/Mockup.tsx" props={[["value / onIonInput", "Controlled text. Read event.detail.value and preserve the draft on errors."], ["maxlength", "500 characters for the phone question composer."], ["label / labelPlacement", "Provide a visible name for single-line fields; the chat composer also needs an accessible name."], ["helperText / errorText", "Associated help and recovery. Ionic error text uses ion-invalid and ion-touched states."], ["getInputElement / setFocus", "Use Ionic’s methods when the native field is needed for sizing or focus."], ["disabled", "Keep the value visible and explain the reason outside the control."]]} tokens={['--card', '--foreground', '--muted-foreground', '--input', '--ring', '--destructive', '--disabled', '--disabled-foreground', '--type-body-size']} />
  </>
}

function SelectPage() {
  const [place, setPlace] = useState<PlaceId>('coit')
  return <>
    <p>Use <code>IonSelect</code> with <code>IonSelectOption</code> for one choice from a longer list. The phone uses this pattern for the subject and neighborhood.</p>
    <Section title="Options and selection"><div className="ds-panel dse-form"><div className="dse-field"><IonSelect mode="ios" interface="popover" interfaceOptions={{ cssClass: 'dse-ionic-preview' }} label="Prepared place example" labelPlacement="stacked" value={place} onIonChange={event => setPlace(event.detail.value as PlaceId)} aria-describedby="dse-select-help">{placeIds.map(id => <IonSelectOption key={id} value={id}>{places[id].name}</IonSelectOption>)}</IonSelect><p id="dse-select-help">Choose which prepared place description to inspect.</p></div><div className="dse-selection" role="status"><strong>{places[place].name}</strong><p>{places[place].reason}</p></div><div className="dse-field"><IonSelect mode="ios" interface="popover" label="Unavailable selection" labelPlacement="stacked" disabled value="example" aria-describedby="dse-disabled-select-help"><IonSelectOption value="example">Telegraph Hill example</IonSelectOption></IonSelect><p id="dse-disabled-select-help">Only this prepared area is available in the specimen.</p></div></div><p>Ionic manages opening, option selection and dismissal. In the phone mockup, keep the resulting overlay inside the device frame; this desktop documentation specimen can use the page overlay.</p></Section>
    <Code>{'<IonSelect mode="ios" interface="popover" label="Neighborhood"\n  value={area} onIonChange={event => setArea(event.detail.value)}>\n  <IonSelectOption value="grand-central">Around Grand Central</IonSelectOption>\n</IonSelect>'}</Code>
    <Contract implementation="The phone uses IonSelect and IonSelectOption directly. This live specimen uses prepared place data." path="studio/Mockup.tsx" props={[["value / onIonChange", "Controlled selection. Read event.detail.value."], ["IonSelectOption value", "A stable key for each human-readable choice."], ["label / labelPlacement", "Visible accessible label and position."], ["interface / interfaceOptions", "Use the appropriate Ionic overlay and keep phone overlays contained."], ["disabled", "Prevents selection while showing the current value."]]} tokens={['--card', '--foreground', '--muted-foreground', '--input', '--ring', '--disabled', '--disabled-foreground', '--type-body-size']} />
  </>
}

function AccordionPage() {
  return <>
    <p>The marketing FAQ retains the existing Radix accordion. It is separate from the phone’s Ionic controls. Use it for optional supporting detail; keep the first answer and its source visible.</p>
    <Section title="Single open section"><div className="ds-panel dse-accordion"><Accordion type="single" collapsible><AccordionItem value="preview"><AccordionTrigger>What can I try in the example?</AccordionTrigger><AccordionContent>Select prepared places, change interests and try the sourced questions. Full map exploration and live answers are still being built.</AccordionContent></AccordionItem><AccordionItem value="history"><AccordionTrigger>Where is my history saved?</AccordionTrigger><AccordionContent>The product example saves choices and drafts in this browser when storage is available. It does not sync between devices; clearing browser data removes that history.</AccordionContent></AccordionItem><AccordionItem value="disabled" disabled><AccordionTrigger>Unavailable example section</AccordionTrigger><AccordionContent>This disabled section cannot be opened.</AccordionContent></AccordionItem></Accordion></div><p>Enter or Space opens a focused section. Arrow keys move between enabled triggers. The disabled example cannot be activated. Expanded state and content relationships come from Radix.</p></Section>
    <Code>{'<Accordion type="single" collapsible>\n  <AccordionItem value="sources">\n    <AccordionTrigger>Where does this answer come from?</AccordionTrigger>\n    <AccordionContent>Supporting context.</AccordionContent>\n  </AccordionItem>\n</Accordion>'}</Code>
    <Contract implementation="Existing exports wrap Radix Accordion and preserve its native API." path="components/ui/accordion.tsx" props={[["Accordion", "Radix Root. Use type=single with collapsible for the current FAQ pattern."], ["AccordionItem", "Requires a stable value. Accepts disabled."], ["AccordionTrigger", "Renders a heading and button, including the existing Plus icon."], ["AccordionContent", "Provides the associated expandable content region."], ["value / defaultValue / onValueChange", "Controlled or uncontrolled expansion through the Radix Root props."]]} tokens={['--foreground', '--muted-foreground', '--muted', '--text-brand', '--border', '--ring', '--focus-width', '--focus-offset', '--motion-normal', '--ease-standard']} />
  </>
}

function UiPatternsPage() {
  const [savedView, setSavedView] = useState(false)
  const [showRecovery, setShowRecovery] = useState(true)
  const [attachment, setAttachment] = useState('No attachment action chosen.')
  const attachmentTriggerId = `dse-attachments-${useId().replace(/:/g, '')}`
  return <>
    <p>UI patterns combine the same Ionic components used in the phone. These live specimens keep their state in the documentation and make no network requests.</p>
    <Section title="Short question form"><div className="ds-panel"><QuestionForm id="dse-pattern" /></div><p>Keep context in the label, suggestions close to the composer and sources beside the answer. Errors preserve the draft and provide a working way forward.</p></Section>
    <Section title="Lists and empty states"><div className="ds-panel"><IonList mode="ios" lines="full" aria-label="Documentation view examples"><IonItem mode="ios" button detail onClick={() => setSavedView(false)} aria-current={!savedView ? 'page' : undefined}><IonIcon icon={compassOutline} slot="start" aria-hidden="true" /><IonLabel>Prepared places</IonLabel><IonBadge slot="end">3</IonBadge></IonItem><IonItem mode="ios" button detail onClick={() => setSavedView(true)} aria-current={savedView ? 'page' : undefined}><IonIcon icon={bookmarkOutline} slot="start" aria-hidden="true" /><IonLabel>Saved places</IonLabel><IonNote slot="end">Empty example</IonNote></IonItem></IonList>{savedView ? <div className="dse-empty"><IonIcon icon={bookmarkOutline} className="dse-icon-lg" aria-hidden="true" /><h3>No saved places yet.</h3><p>Saved places appear here when you return.</p><Button variant="secondary" onClick={() => setSavedView(false)}>Explore places<IonIcon icon={arrowForwardOutline} slot="end" aria-hidden="true" /></Button></div> : <div className="dse-selection"><strong>Telegraph Hill example</strong><p>Select Saved places to inspect the empty state. The phone uses these list components for conversation history and route stops.</p></div>}</div><p>Use <code>IonLabel</code> for the main text, <code>IonNote</code> for supporting metadata and <code>IonBadge</code> for a compact count or status. The empty state names the situation and offers a next action.</p></Section>
    <Section title="Attachment popover"><div className="ds-panel"><Button id={attachmentTriggerId} variant="secondary" aria-label="Open example attachment choices"><IonIcon icon={addOutline} slot="start" aria-hidden="true" />Add attachment</Button><IonPopover mode="ios" className="dse-ionic-preview" trigger={attachmentTriggerId} side="top" alignment="start" dismissOnSelect aria-label="Example attachment choices"><IonList mode="ios" lines="full">{[{ label: 'Camera', icon: cameraOutline }, { label: 'Photo', icon: imageOutline }, { label: 'File', icon: documentOutline }].map(option => <IonItem mode="ios" button detail={false} key={option.label} onClick={() => setAttachment(`${option.label} selected. This documentation example does not open a device picker.`)}><IonIcon icon={option.icon} slot="start" aria-hidden="true" /><IonLabel>{option.label}</IonLabel></IonItem>)}</IonList></IonPopover><p className="dse-status" role="status">{attachment}</p></div><p>The phone uses the same vertical action list in a popover above +. Its shared adapter keeps the overlay inside the device frame. This page specimen demonstrates Ionic’s trigger and dismissal behavior without requesting camera or file access.</p></Section>
    <Section title="Loading and feedback"><div className="ds-panel dse-stack"><div className="dse-loading-specimen"><IonSpinner name="lines" aria-hidden="true" /><div><strong>Finding places</strong><p>Loading specimen. No request is running.</p></div></div>{showRecovery ? <div className="dse-feedback dse-feedback-warning"><strong>Try a suggested question</strong><p>This example has prepared answers. Your draft is still here.</p><Button variant="ghost" onClick={() => setShowRecovery(false)}>Dismiss example notice</Button></div> : <Button variant="secondary" onClick={() => setShowRecovery(true)}>Show recovery notice</Button>}<div className="dse-feedback dse-feedback-success"><strong>Places updated.</strong><p>Kept places stay in your group. Static success specimen.</p></div></div><p>Pair <code>IonSpinner</code> with a readable label. Reserve <code>role="status"</code> for actual updates and <code>role="alert"</code> for an error that needs attention. Static specimens do not announce an event.</p></Section>
    <Contract implementation="Live documentation compositions use the phone app’s Ionic component family." path="studio/Mockup.tsx" props={[["Question form", "IonInput, suggested-question IosButtons and an adjacent source."], ["Lists", "IonList, IonItem, IonLabel, IonNote and IonBadge."], ["Popover", "IonPopover with an IonList of actions. The phone adds containment through its shared adapter."], ["Empty state", "Clear explanation and one relevant recovery action."], ["Loading / feedback", "IonSpinner with readable status and honest prepared-preview limits."]]} tokens={['--card', '--foreground', '--muted-foreground', '--accent', '--accent-foreground', '--success', '--success-foreground', '--warning', '--warning-foreground', '--space-md', '--space-lg']} />
  </>
}

function ScenarioPatternsPage() {
  const [query, setQuery] = useState('')
  const [pending, setPending] = useState<Interest>('A little of everything')
  const [interest, setInterest] = useState<Interest>('A little of everything')
  const [kept, setKept] = useState<PlaceId[]>([])
  const [message, setMessage] = useState('Search, filter or save the three prepared places. Changes stay in this documentation preview.')
  const group = [...new Set([...suggestionsFor(interest), ...kept])]
  const visible = group.filter(id => `${places[id].name} ${places[id].category}`.toLowerCase().includes(query.toLowerCase()))
  function save(id: PlaceId) {
    const alreadyKept = kept.includes(id)
    setKept(current => alreadyKept ? current.filter(item => item !== id) : [...current, id])
    setMessage(`${places[id].name} ${alreadyKept ? 'removed from' : 'saved in'} this documentation preview.`)
  }
  return <>
    <p>Scenario patterns connect a choice, its result and a way to recover. This prepared-place demonstration exercises Ionic controls without changing phone conversations or walk progress.</p>
    <Section title="Search, filter and keep"><div className="ds-panel dse-workflow"><div className="dse-field"><IonInput mode="ios" type="search" label="Search example places" labelPlacement="stacked" value={query} onIonInput={event => setQuery(String(event.detail.value ?? ''))} placeholder="Try Coit Tower"><IonIcon icon={searchOutline} slot="start" aria-hidden="true" /></IonInput></div><div className="dse-field"><span id="dse-scenario-interest">What are you curious about?</span><IonRadioGroup value={pending} onIonChange={event => setPending(event.detail.value as Interest)} aria-labelledby="dse-scenario-interest"><IonList mode="ios" lines="full">{interestOptions.map(option => <IonItem mode="ios" key={option.value}><IonRadio mode="ios" value={option.value} labelPlacement="start" justify="space-between">{option.label}</IonRadio></IonItem>)}</IonList></IonRadioGroup></div><div className="dse-workflow-action"><Button variant="secondary" onClick={() => { setInterest(pending); setMessage('Places updated. Kept places stay in your group.') }} disabled={pending === interest}>Update places<IonIcon icon={arrowForwardOutline} slot="end" aria-hidden="true" /></Button><p>{pending === interest ? `Showing ${interest.toLowerCase()}.` : 'New interest selected. Update places to apply it.'}</p></div><p className="dse-result-count" role="status">{visible.length} {visible.length === 1 ? 'place' : 'places'} shown · {kept.length} saved</p><IonList mode="ios" lines="full" aria-label="Prepared place results">{visible.map(id => <IonItem mode="ios" key={id}><IonLabel><strong>{places[id].name}</strong><p>{places[id].category}</p></IonLabel><Button slot="end" variant={kept.includes(id) ? 'default' : 'ghost'} aria-label={`Save ${places[id].name}`} aria-pressed={kept.includes(id)} onClick={() => save(id)}><IonIcon icon={kept.includes(id) ? bookmark : bookmarkOutline} slot="start" aria-hidden="true" />{kept.includes(id) ? 'Saved' : 'Save'}</Button></IonItem>)}</IonList>{!visible.length && <div className="dse-empty"><IonIcon icon={searchOutline} className="dse-icon-lg" aria-hidden="true" /><h3>No matching places.</h3><p>Try Coit Tower, Telegraph Hill or Filbert Steps.</p><Button variant="secondary" onClick={() => { setQuery(''); setMessage('Search cleared.') }}>Clear search</Button></div>}<p className="dse-status" role="status">{message}</p></div></Section>
    <Section title="Sequence and recovery"><div className="dse-scenario-rules"><div><h3>Search</h3><p>Match the name or category within the prepared group. Keep the query visible. If nothing matches, explain the scope and offer Clear search.</p></div><div><h3>Update interests</h3><p>Keep the pending selection separate. Disable Update places until it changes. Apply explicitly and retain saved places in the group.</p></div><div><h3>Save and undo</h3><p>Show the saved state on the same control and let the person undo it. This specimen keeps state only while mounted.</p></div></div></Section>
    <Section title="Product scope"><p>This is a documentation demonstration using prepared place data. The phone mockup has map-based chat, attachment choices and simulated walks. It does not make bookings or manage accounts.</p><a className="ds-inline-code-link" href="#mockup">Open the phone app preview <IonIcon icon={arrowForwardOutline} className="dse-icon-sm" aria-hidden="true" /></a></Section>
    <Contract implementation="This documentation-only sequence combines the current Ionic controls with prepared-place data." path="studio/DesignSystemExamples.tsx" props={[["Search", "IonInput with a case-insensitive name/category match in the prepared group."], ["Filter", "IonRadioGroup selects a pending preference."], ["Update", "IosButton commits the preference explicitly; disabled when unchanged."], ["Save", "IosButton with a stable accessible label, aria-pressed and an IonIcon state."], ["Recovery", "Clear unmatched search and preserve saved places when interests change."]]} tokens={['--card', '--foreground', '--muted-foreground', '--input', '--accent', '--accent-foreground', '--ring', '--primary', '--secondary', '--border', '--space-md', '--space-lg']} />
    <p className="ds-note">Prepared content and filtering data come from <a className="ds-inline-code-link" href={source('lib/places.ts')} target="_blank" rel="noreferrer">places.ts</a>.</p>
  </>
}

export default function DesignSystemExamples({ page }: { page: string }) {
  const pages: Record<string, ReactNode> = { icons: <IconsPage />, 'ui-patterns': <UiPatternsPage />, 'scenario-patterns': <ScenarioPatternsPage />, button: <ButtonPage />, toggle: <TogglePage />, radio: <RadioPage />, 'text-input': <TextInputPage />, select: <SelectPage />, accordion: <AccordionPage /> }
  return <div className="dse-content dse-ionic-preview" style={ionicPreviewTheme} key={page}>{pages[page] ?? <p>No example page exists for this section.</p>}</div>
}
